Repository fga-eps-mds/2019.2-Alohomora, pull requests merged in 2019-09, with the labels that each got.

#25 #12 - Pasta de arquivos markdown
  docs/about.md
  docs/index.md
  docs/mkdocs.yml
Labels: bug, documentacao, help wanted, melhoria

#29 Adicionada a funcionalidade de criar 'users' e 'visitors' no banco de…
  app/portariaVirtual/accounts/admin.py
Labels: implementacao

#32 #12 - Template de documentação
  docs/about.md
  docs/gerencia/EAP.md
  docs/gerencia/plano_gcs.md
  docs/index.md
  docs/mkdocs.yml
  docs/projeto/doc_visao.md
  docs/sprints/sprint_0.md
  docs/sprints/sprint_1.md
  docs/sprints/sprint_2.md
  docs/sprints/sprint_3.md
  mkdocs.yml
Labels: documentacao, help wanted, melhoria

#42 20 estrutura do condominio
  app/accounts/__init__.py
  app/accounts/admin.py
  app/accounts/apps.py
  app/accounts/migrations/0001_initial.py
  app/accounts/migrations/0002_auto_20190913_2210.py
  app/accounts/migrations/__init__.py
  app/accounts/models.py
  app/accounts/schema.py
  app/accounts/tests/__init__.py
  app/accounts/tests/test_models.py
  app/accounts/views.py
  app/alohomora/__init__.py
  app/alohomora/schema.py
  app/alohomora/settings.py
  app/alohomora/urls.py
  app/alohomora/wsgi.py
  app/condos/__init__.py
  app/condos/admin.py
  app/condos/apps.py
  app/condos/migrations/0001_initial.py
  app/condos/migrations/__init__.py
  app/condos/models.py
  app/condos/schema.py
  app/condos/tests.py
  app/condos/views.py
  app/manage.py
  app/portariaVirtual/schema.py
Labels: implementacao

#78 Criando nova query 'apartments' e corrigindo a 'apartment'
  app/condos/schema.py
  app/condos/tests.py
Labels: bug

#82 Query individual para user/visitor
  .pylintrc
  .travis.yml
  app/accounts/schema.py
  app/accounts/tests/test_schema.py
Labels: melhoria

#46 #14 - Escrever EAP
  docs/docs/gerencia/EAP.md
  docs/docs/img/eap.png
  docs/docs/index.md
Labels: documentacao

#83 #65 - Escrever o TAP
  docs/docs/gerencia/TAP.md
  docs/mkdocs.yml
Labels: documentacao, help wanted

#79 Bot para cadastro de usuários
  .pylintrc
  bot/main.py
  docker-compose.yml
  docker/bot/Dockerfile
  docker/bot/requirements.txt
Labels: implementacao
